import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });



export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>some title here</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main>
        {data.map((ev) => (
          <Link key={ev.id} href={`/events/${ev.id}`} passHref>
            <h2>{ev.title}</h2>
            <div style={{width: '200px', height: '200px', position: 'relative'}}>
              <Image alt={ev.title} src={ev.image} layout='fill' />
            </div>
            {/* <img src={ev.image} alt="" /> */}
            <p>{ev.description}</p>
          </Link>
        ))}
      </main>

    </>
  );
}

export async function getServerSideProps() {
  const { events_categories } = await import("/data/data.json");
  // console.log(events_categories);
  return {
    props: {
      data: events_categories,
    },
  };
}